
name: Linting

on:
  push:
    branches: 
      - prebuild
      - build-local
  
  pull_request:
    branches: 
      - main

jobs:
  
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Hadolint
        run: |
          curl -sSL https://github.com/hadolint/hadolint/releases/download/v2.12.1-beta/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
          chmod +x /usr/local/bin/hadolint

      - name: Lint Dockerfile
        run: hadolint Dockerfile

  lint-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up ShellCheck
        run: sudo apt install shellcheck
      
      - name: Lint shell scripts
        run: |
          find . -type f -name '*.sh' -exec shellcheck {} +

  lint-markdown:
    name: Lint Markdown file(s)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup node 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Run markdown lint
        env:
          REPORT_ONLY: true
          SHOW_ERRORS: true
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/markdown-lint/master/pipeline.sh)
 
    